Rails.application.routes.draw do

  #testing trial
  get 'about', to: 'users#about'

  # Initial Routes for the User, Signup, Login, Logout
  root 'users#home_method'

  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get '/logout' => 'sessions#destroy'

  # GOOGLE AUTHENTICATION
  get 'auth/google_oauth2', to: redirect('auth/google_oauth2'), as: 'google_login'
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')

  resources :users, only: [:new, :create]

  # Manual routing for delete since there will not be a show page for situations... situations show redirects to index.
  get '/situations/:id/destroy' => 'situations#destroy'
  get '/situations/:id/edit' => 'situations#edit'

  # Nested Routing for Phrases. NOTE: Phrases "Show" redirects to situations/:id/phrases index (index serves as show; show redirects to index)
  resources :situations do
    resources :phrases, except: [:destroy, :edit, :update]
  end

  # Manual routing for phrase edit that redirects to index
  get "/situations/:situation_id/phrases/:phrase_id/edit" => 'phrases#edit'
  patch "/situations/:situation_id/phrases/:phrase_id" => 'phrases#update'
  get "/situations/:situation_id/phrases/:phrase_id/destroy" => 'phrases#destroy'
  get "/situations/:situation_id/phrases" => "phrases#index"


  get '/users/:id/flashcards' => "scores#index"
  post '/users/:id/flashcards' => "scores#index"

  get '/users/:id/flashcards/study_time' => "scores#show" #Routes to flashcard_first_view the english phonetic is not shown here...
  get '/users/:id/flashcards/study_time' => "scores#edit" #Routes to flashcard_with_score "show phonetic will bring you to an edit page, which allows the user to edit a score and reveals phonetic"
  post '/users/:id/flashcards/study_time' => "scores#update" #this will update the score_id for the phrase and also change the familiarity rank

  #Routes to Select Scores (this should mimic the situaton index checkboxes)... this should be on scores controller



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html <- this line was autogenerated.

  #get '*path' => redirect('/') <--not really sure how this works, will use it if I can figure it out.
end
