class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy] <--this was autogenerated

  # GET /users/new THIS IS THE SIGN UP FORM
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json

  def create
    @user = User.new(user_params)
    if @user.save
      #login the user
      session[:user_id] = @user.id
      redirect_to languages_path
    else
      render :new
    end
  end


  #OLD CREATE GENERATED BY SCAFFOLDING BELOW
  #def create
  #  @user = User.new(user_params)

  #  respond_to do |format|
  #    if @user.save
  #      session[:user_id] = @user.id
  #      format.html { redirect_to @user, notice: 'User was successfully created.' }
  #      format.json { render :show, status: :created, location: @user }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @user.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end


  #def destroy
  #  @user.destroy
  #  respond_to do |format|
  #    format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :beta_key, :password) #password_digest was previously password...if you left as password_digest it would be stored unhashed (or something like that)
    end
end
